### ISSUE TITLE
Typo in blas library name

### ISSUE THREAD

**Issue by frobnitzem** [mpbelhorn/olcf-spack-environments#2]
`blas: [openblas, mlk]`
should be 
`blas: [openblas, mkl]`

https://github.com/mpbelhorn/olcf-spack-environments/blob/5ced64683421bda3447867ea6aaf4e2ae189370f/hosts/andes/envs/base/spack.yaml#L434

**Comment by mpbelhorn** [comment]
Fixed in a4339e421a45b866c8c50c0f9d5a2e408dcf0dcf
